export enum Environment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
  TEST = 'test',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
}

export enum RoleEnum {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  FLEET_MANAGER = 'FLEET_MANAGER',
  OPERATOR = 'OPERATOR',
  DRIVER = 'DRIVER',
  READ_ONLY_USER = 'READ_ONLY_USER',
}

export enum PermissionEnum {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  FLEET_MANAGEMENT = 'FLEET_MANAGEMENT',
  VEHICLE_MANAGEMENT = 'VEHICLE_MANAGEMENT',
  TELEMETRY = 'TELEMETRY',
  TRIPS = 'TRIPS',
  LOCATION_READ = 'LOCATION_READ',
  LOCATION_MANAGE = 'LOCATION_MANAGE',
  TRIP_READ = 'TRIP_READ',
  TRIP_MANAGE = 'TRIP_MANAGE',
  GEOFENCE_MANAGE = 'GEOFENCE_MANAGE',
  DIAGNOSTICS_READ = 'DIAGNOSTICS_READ',
  DIAGNOSTICS_MANAGE = 'DIAGNOSTICS_MANAGE',
  MAINTENANCE_READ = 'MAINTENANCE_READ',
  MAINTENANCE_MANAGE = 'MAINTENANCE_MANAGE',
  DRIVER_BEHAVIOUR_READ = 'DRIVER_BEHAVIOUR_READ',
  DRIVER_BEHAVIOUR_MANAGE = 'DRIVER_BEHAVIOUR_MANAGE',
  FLEET_ANALYTICS = 'FLEET_ANALYTICS',
  COMMAND_EXECUTE = 'COMMAND_EXECUTE',
  COMMAND_READ = 'COMMAND_READ',
  OTA_READ = 'OTA_READ',
  OTA_MANAGE = 'OTA_MANAGE',
  FIRMWARE_MANAGE = 'FIRMWARE_MANAGE',
  FLEET_COMMAND = 'FLEET_COMMAND',
  FLEET_OTA = 'FLEET_OTA',
  NOTIFICATION_READ = 'NOTIFICATION_READ',
  NOTIFICATION_MANAGE = 'NOTIFICATION_MANAGE',
  ANALYTICS_READ = 'ANALYTICS_READ',
  ANALYTICS_EXPORT = 'ANALYTICS_EXPORT',
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',
  REPORTS_READ = 'REPORTS_READ',
  REPORTS_EXPORT = 'REPORTS_EXPORT',
  REPORTS_MANAGE = 'REPORTS_MANAGE',
  AUDIT_READ = 'AUDIT_READ',
  AUDIT_MANAGE = 'AUDIT_MANAGE',
  ADMIN_READ = 'ADMIN_READ',
  ADMIN_MANAGE = 'ADMIN_MANAGE',
  FEATURE_FLAGS_MANAGE = 'FEATURE_FLAGS_MANAGE',
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',
  API_KEYS_MANAGE = 'API_KEYS_MANAGE',
  WEBHOOKS_MANAGE = 'WEBHOOKS_MANAGE',
  DIAGNOSTICS = 'DIAGNOSTICS',
  REPORTS = 'REPORTS',
  OTA = 'OTA',
  NOTIFICATIONS = 'NOTIFICATIONS',
  ANALYTICS = 'ANALYTICS',
  AUDIT = 'AUDIT',
  ADMIN = 'ADMIN',
}

export enum FleetStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum VehicleStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  RETIRED = 'RETIRED',
  SOLD = 'SOLD',
  SUSPENDED = 'SUSPENDED',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum DriverAssignmentStatus {
  ACTIVE = 'ACTIVE',
  RELEASED = 'RELEASED',
  TRANSFERRED = 'TRANSFERRED',
}

export enum PairingStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum TripStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum GeofenceType {
  CIRCLE = 'CIRCLE',
  POLYGON = 'POLYGON',
}

export enum DtcCategory {
  ENGINE = 'ENGINE',
  TRANSMISSION = 'TRANSMISSION',
  ELECTRICAL = 'ELECTRICAL',
  BATTERY = 'BATTERY',
  COOLING = 'COOLING',
  FUEL = 'FUEL',
  BRAKE = 'BRAKE',
  SUSPENSION = 'SUSPENSION',
  STEERING = 'STEERING',
  ABS = 'ABS',
  AIRBAG = 'AIRBAG',
  EMISSION = 'EMISSION',
  TYRE = 'TYRE',
  CHARGING = 'CHARGING',
  UNKNOWN = 'UNKNOWN',
}

export enum DtcSeverity {
  INFO = 'INFO',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum DtcStatus {
  ACTIVE = 'ACTIVE',
  RESOLVED = 'RESOLVED',
}

export enum MaintenancePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum BehaviourEventType {
  HARSH_BRAKING = 'HARSH_BRAKING',
  HARSH_ACCELERATION = 'HARSH_ACCELERATION',
  RAPID_CORNERING = 'RAPID_CORNERING',
  OVERSPEED = 'OVERSPEED',
  RAPID_DECELERATION = 'RAPID_DECELERATION',
  LONG_IDLING = 'LONG_IDLING',
  ENGINE_OVER_REVVING = 'ENGINE_OVER_REVVING',
  HIGH_RPM = 'HIGH_RPM',
  AGGRESSIVE_DRIVING = 'AGGRESSIVE_DRIVING',
  NIGHT_DRIVING = 'NIGHT_DRIVING',
  SEATBELT_VIOLATION = 'SEATBELT_VIOLATION',
  DOOR_OPEN_MOVING = 'DOOR_OPEN_MOVING',
}

export enum RankingPeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}

export enum CommandType {
  LOCK_DOORS = 'LOCK_DOORS',
  UNLOCK_DOORS = 'UNLOCK_DOORS',
  START_ENGINE = 'START_ENGINE',
  STOP_ENGINE = 'STOP_ENGINE',
  FLASH_LIGHTS = 'FLASH_LIGHTS',
  HONK_HORN = 'HONK_HORN',
  ENABLE_IMMOBILIZER = 'ENABLE_IMMOBILIZER',
  DISABLE_IMMOBILIZER = 'DISABLE_IMMOBILIZER',
  OPEN_TRUNK = 'OPEN_TRUNK',
  CLOSE_TRUNK = 'CLOSE_TRUNK',
  ACTIVATE_HAZARD_LIGHTS = 'ACTIVATE_HAZARD_LIGHTS',
  DEACTIVATE_HAZARD_LIGHTS = 'DEACTIVATE_HAZARD_LIGHTS',
  START_CLIMATE_CONTROL = 'START_CLIMATE_CONTROL',
  STOP_CLIMATE_CONTROL = 'STOP_CLIMATE_CONTROL',
  SET_CABIN_TEMPERATURE = 'SET_CABIN_TEMPERATURE',
  ENABLE_DEFROST = 'ENABLE_DEFROST',
  START_CHARGING = 'START_CHARGING',
  STOP_CHARGING = 'STOP_CHARGING',
  SET_CHARGE_LIMIT = 'SET_CHARGE_LIMIT',
  RESET_SERVICE_REMINDER = 'RESET_SERVICE_REMINDER',
  CUSTOM_OEM_COMMAND = 'CUSTOM_OEM_COMMAND',
}

export enum CommandStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  EXECUTING = 'EXECUTING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  TIMED_OUT = 'TIMED_OUT',
  CANCELLED = 'CANCELLED',
}

export enum CommandPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RolloutType {
  IMMEDIATE = 'IMMEDIATE',
  SCHEDULED = 'SCHEDULED',
  PERCENTAGE = 'PERCENTAGE',
  FLEET = 'FLEET',
  REGION = 'REGION',
  MANUAL_APPROVAL = 'MANUAL_APPROVAL',
}

export enum OtaCampaignStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum OtaStatus {
  PENDING = 'PENDING',
  DOWNLOADING = 'DOWNLOADING',
  INSTALLING = 'INSTALLING',
  REBOOTING = 'REBOOTING',
  VERIFYING = 'VERIFYING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  ROLLED_BACK = 'ROLLED_BACK',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
  WEBHOOK = 'WEBHOOK',
}

export enum NotificationCategory {
  AUTHENTICATION = 'AUTHENTICATION',
  FLEET = 'FLEET',
  VEHICLE = 'VEHICLE',
  TRIP = 'TRIP',
  DIAGNOSTICS = 'DIAGNOSTICS',
  MAINTENANCE = 'MAINTENANCE',
  REMOTE_COMMAND = 'REMOTE_COMMAND',
  OTA = 'OTA',
  GEOFENCE = 'GEOFENCE',
  DRIVER_BEHAVIOUR = 'DRIVER_BEHAVIOUR',
  SECURITY = 'SECURITY',
  ANALYTICS = 'ANALYTICS',
  SYSTEM = 'SYSTEM',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  SENDING = 'SENDING',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum AnalyticsPeriod {
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}

export enum ReportType {
  FLEET = 'FLEET',
  VEHICLE = 'VEHICLE',
  TRIP = 'TRIP',
  DRIVER = 'DRIVER',
  MAINTENANCE = 'MAINTENANCE',
  DIAGNOSTICS = 'DIAGNOSTICS',
  FUEL = 'FUEL',
  BATTERY = 'BATTERY',
  HEALTH = 'HEALTH',
  SAFETY = 'SAFETY',
  NOTIFICATION = 'NOTIFICATION',
  OTA = 'OTA',
  SYSTEM_USAGE = 'SYSTEM_USAGE',
  AUDIT = 'AUDIT',
  CUSTOM = 'CUSTOM',
}

export enum ExportFormat {
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  CSV = 'CSV',
  JSON = 'JSON',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum FuelType {
  GASOLINE = 'GASOLINE',
  DIESEL = 'DIESEL',
  ELECTRIC = 'ELECTRIC',
  HYBRID = 'HYBRID',
  PLUG_IN_HYBRID = 'PLUG_IN_HYBRID',
  HYDROGEN = 'HYDROGEN',
}

export enum Transmission {
  MANUAL = 'MANUAL',
  AUTOMATIC = 'AUTOMATIC',
  SINGLE_SPEED_EV = 'SINGLE_SPEED_EV',
  CVT = 'CVT',
}

export enum VehicleType {
  SEDAN = 'SEDAN',
  SUV = 'SUV',
  TRUCK = 'TRUCK',
  VAN = 'VAN',
  BUS = 'BUS',
  COUPE = 'COUPE',
  HATCHBACK = 'HATCHBACK',
}

export enum LogLevel {
  FATAL = 'fatal',
  ERROR = 'error',
  WARN = 'warn',
  INFO = 'info',
  DEBUG = 'debug',
  TRACE = 'trace',
}
