export const APP_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
  CORRELATION_ID_HEADER: 'x-correlation-id',
  REQUEST_ID_HEADER: 'x-request-id',
};

export const AUTH_CONSTANTS = {
  JWT_SECRET: process.env.JWT_SECRET || 'vis-super-secret-jwt-key',
  JWT_ACCESS_EXPIRATION: '15m',
  JWT_REFRESH_EXPIRATION: '7d',
  BCRYPT_SALT_ROUNDS: 12,
  MAX_FAILED_LOGIN_ATTEMPTS: 5,
  ACCOUNT_LOCKOUT_DURATION_MINUTES: 30,
  VERIFICATION_TOKEN_EXPIRATION_HOURS: 24,
  PASSWORD_RESET_TOKEN_EXPIRATION_MINUTES: 60,
  PASSWORD_HISTORY_LIMIT: 5,
};

export const VEHICLE_CONSTANTS = {
  PAIRING_CODE_EXPIRATION_MINUTES: 15,
  PAIRING_CODE_LENGTH: 6,
  VIN_LENGTH: 17,
};

export const TRIP_CONSTANTS = {
  SPEED_THRESHOLD_KMH: 5.0,
  IDLE_TIMEOUT_MINUTES: 15,
};

export const DIAGNOSTIC_CONSTANTS = {
  CRITICAL_ENGINE_TEMP_CELSIUS: 110.0,
  CRITICAL_COOLANT_TEMP_CELSIUS: 105.0,
  LOW_BATTERY_VOLTAGE: 350.0,
  LOW_OIL_PRESSURE_PSI: 20.0,
  MIN_TYRE_PRESSURE_PSI: 26.0,
  MAX_TYRE_PRESSURE_PSI: 40.0,
};

export const BEHAVIOUR_CONSTANTS = {
  OVERSPEED_THRESHOLD_KMH: 120.0,
  HIGH_RPM_THRESHOLD: 4000,
  HARSH_BRAKE_DECEL_THRESHOLD: 20.0,
  HARSH_ACCEL_THRESHOLD: 25.0,
  RAPID_CORNERING_HEADING_CHANGE: 45.0,
};

export const COMMAND_CONSTANTS = {
  DEFAULT_COMMAND_TIMEOUT_SECONDS: 30,
  MAX_COMMAND_RETRIES: 3,
  COMMAND_EXPONENTIAL_BACKOFF_MS: 1000,
};

export const OTA_CONSTANTS = {
  MAX_ROLLOUT_PERCENTAGE: 100,
  DEFAULT_BATCH_SIZE: 50,
};

export const NOTIFICATION_CONSTANTS = {
  MAX_NOTIFICATION_RETRIES: 3,
  EXPONENTIAL_BACKOFF_BASE_MS: 1000,
  DEFAULT_TEMPLATE_VERSION: 1,
};

export const ANALYTICS_CONSTANTS = {
  HOURLY_CRON_SCHEDULE: '0 * * * *',
  DAILY_CRON_SCHEDULE: '0 0 * * *',
  WEEKLY_CRON_SCHEDULE: '0 0 * * 0',
  MONTHLY_CRON_SCHEDULE: '0 0 1 * *',
  CACHE_TTL_DASHBOARD_SECONDS: 300,
};

export const REPORTING_CONSTANTS = {
  DEFAULT_EXPIRATION_DAYS: 30,
  MAX_EXPORT_ROWS: 10000,
};

export const ADMIN_CONSTANTS = {
  API_KEY_PREFIX: 'vis_live_',
  WEBHOOK_TIMEOUT_MS: 5000,
  WEBHOOK_MAX_RETRIES: 3,
};

export const SERVICES = {
  API_GATEWAY: 'API_GATEWAY',
  AUTH_SERVICE: 'AUTH_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  FLEET_SERVICE: 'FLEET_SERVICE',
  VEHICLE_SERVICE: 'VEHICLE_SERVICE',
  TELEMETRY_SERVICE: 'TELEMETRY_SERVICE',
  LOCATION_SERVICE: 'LOCATION_SERVICE',
  TRIP_SERVICE: 'TRIP_SERVICE',
  DIAGNOSTICS_SERVICE: 'DIAGNOSTICS_SERVICE',
  DRIVER_BEHAVIOUR_SERVICE: 'DRIVER_BEHAVIOUR_SERVICE',
  REMOTE_COMMAND_SERVICE: 'REMOTE_COMMAND_SERVICE',
  OTA_SERVICE: 'OTA_SERVICE',
  NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE',
  ANALYTICS_SERVICE: 'ANALYTICS_SERVICE',
  REPORTING_SERVICE: 'REPORTING_SERVICE',
  AUDIT_SERVICE: 'AUDIT_SERVICE',
  ADMIN_SERVICE: 'ADMIN_SERVICE',
};
