apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vis-default-deny-ingress
  namespace: vis-production
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vis-allow-api-gateway
  namespace: vis-production
spec:
  podSelector:
    matchLabels:
      app: vis-api-gateway
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
  policyTypes:
    - Ingress
